### PR TITLE
Update `"panic"` to `"panic-strategy"`

### LINKED ISSUE #391: Second Edition: Post 2: still need `panic = "abort"` in `Cargo.toml`, despite the claim that I don't
Second edition post 2 describes adding this line to the target `.json` file:
```json
"panic": "abort",
```
and then mentions: "This has the same effect as the `panic = "abort"` option in our Cargo.toml, so we can remove it from there".

As far as I can tell on my system (macOS 10.13.3), this just isn't true, and I still need `panic="abort"` in my Cargo.toml. Here is some version information:
```
~/X/blog_os (master) $ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.25.0-nightly (4d2d3fc5d 2018-02-13)

~/X/blog_os (master) $ xargo --version
xargo 0.3.10
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
```
And a transcript showing the problem:
```
~/X/blog_os (master) $ cat Cargo.toml
[package]
name = "blog_os"
version = "0.1.0"
authors = ["Donald Pinckney <donald_pinckney@icloud.com>"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
~/X/blog_os (master) $ cat x86_64-unknown-blog_os.json
{
    "llvm-target": "x86_64-unknown-none",
    "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
    "arch": "x86_64",
    "target-endian": "little",
    "target-pointer-width": "64",
    "target-c-int-width": "32",
    "os": "none",
    "executables": true,
    "linker-flavor": "ld",
    "linker": "ld.lld",
    "panic": "abort",
    "disable-redzone": true,
    "features": "-mmx,-sse,+soft-float"

}

~/X/blog_os (master) $ xargo clean
~/X/blog_os (master) $ xargo build --target x86_64-unknown-blog_os
   Compiling blog_os v0.1.0 (file:///Users/donaldpinckney/Xcode/blog_os)
    Finished dev [unoptimized + debuginfo] target(s) in 0.60 secs
~/X/blog_os (master) $ vim Cargo.toml 
~/X/blog_os (master|+1) $ cat Cargo.toml
[package]
name = "blog_os"
version = "0.1.0"
authors = ["Donald Pinckney <donald_pinckney@icloud.com>"]

[dependencies]

~/X/blog_os (master|+1) $ cat x86_64-unknown-blog_os.json
{
    "llvm-target": "x86_64-unknown-none",
    "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
    "arch": "x86_64",
    "target-endian": "little",
    "target-pointer-width": "64",
    "target-c-int-width": "32",
    "os": "none",
    "executables": true,
    "linker-flavor": "ld",
    "linker": "ld.lld",
    "panic": "abort",
    "disable-redzone": true,
    "features": "-mmx,-sse,+soft-float"

}

~/X/blog_os (master|+1) $ xargo clean
~/X/blog_os (master|+1) $ xargo build --target x86_64-unknown-blog_os
   Compiling core v0.0.0 (file:///Users/donaldpinckney/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore)
    Finished release [optimized] target(s) in 15.72 secs
   Compiling blog_os v0.1.0 (file:///Users/donaldpinckney/Xcode/blog_os)
error: language item required, but not found: `eh_personality`

error: aborting due to previous error

error: Could not compile `blog_os`.

To learn more, run the command again with --verbose.
~/X/blog_os (master|+1) $ 
```

### PR DESCRIPTION
**Pull request by toothbrush7777777**
Corrected typo in second edition blog post.

Closes #391.

### CODE REVIEW

**Comment by donald-pinckney** [comment]
Ah, that would make sense. Shouldn’t `blog_os/x86_64-blog_os.json` also be updated?

**Comment by toothbrush7777777** [comment]
@donald-pinckney Yes, you are correct. I missed that one.

**Comment by phil-opp** [comment]
Thanks a lot for reporting and fixing! I wonder why this didn't cause any errors...

**Comment by toothbrush7777777** [comment]
@phil-opp No problem. I noticed when I read the post because I made the same mistake a few months ago.

**Pull request merged**
