### PR TITLE
Experimental Support for Community Translations

### PR DESCRIPTION
**Pull request by phil-opp**
This pull request adds experimental support for community translations as discussed in #682. 

Please feel free to contribute translations to this pull request by filing pull requests against the `translations` branch! The naming convention for translated files is `index.[lang-code].md` where `[lang-code]` is an IETF language tag such as `zh` for Chinese or `de` for German.

Todo (later):

- [ ] Provide a way to switch languages, at least from the index page. We could for example add small flag buttons for supported languages.
- [ ] Translate the introduction on the index page.
- [ ] Translate UI elements, such as the 'All Posts' link or the 'Comments' heading.

~Blocked on https://github.com/getzola/zola/pull/856.~

~Blocked on https://github.com/getzola/zola/pull/811, as we don't want to use a pre-release of Zola.~

### CODE REVIEW

**Comment by phil-opp** [comment]
Note: I'm not sure if `zh` is the best language tag for Chinese. As far as I know there are at least traditional and simplified Chinese, so maybe we need to be more specific here.

**Comment by phil-opp** [comment]
@luojia65 It seems like you already translated some of the content to Chinese at https://github.com/rustcc/writing-an-os-in-rust. Maybe you like to contribute these translations?

**Comment by Rustin-Liu** [comment]
> Note: I'm not sure if `zh` is the best language tag for Chinese. As far as I know there are at least traditional and simplified Chinese, so maybe we need to be more specific here.

Yes, the Traditional Chinese tag is zh_TW and the Simplified Chinese tag is zh_CN.
But I think we can only support Simplified Chinese now. 
Because Simplified Chinese is more widely used, we may consider Traditional Chinese later.

**Comment by phil-opp** [comment]
Thanks for the info! I updated the language tag to `zh-CN`.

**Comment by luojia65** [comment]
> @luojia65 It seems like you already translated some of the content to Chinese at 
> https://github.com/rustcc/writing-an-os-in-rust. Maybe you like to contribute these translations?

Yes I'd love to contribute my translations. If okay, please notify me after the translated site is online, so I could then offer suggestions on Chinese fonts and composing, etc. if applicable.

**Comment by phil-opp** [comment]
> Yes I'd love to contribute my translations.

Awesome! Do you want to create a pull request against the `translations` branch? Alternatively I could also copy the content myself if you don't have the time (I would of course set you as the commit author).



> If okay, please notify me after the translated site is online, so I could then offer suggestions on Chinese fonts and composing, etc. if applicable.

Sure, will do! I plan to put it online without linking it from the normal homepage, so that it is only visible if one knows the URLs. This allows us to check the rendering etc. before we present it to the public.

**Comment by luojia65** [comment]
Oh I do not have time for now (midterms), please do the copy for me :) @phil-opp

**Comment by Rustin-Liu** [comment]
> Oh I do not have time for now (midterms), please do the copy for me :) @phil-opp

I think I can help you.

**Comment by phil-opp** [comment]
@Rustin-Liu 

> I think I can help you.

Great, thanks a lot! I opened a separate PR with an initial copy at https://github.com/phil-opp/blog_os/pull/694. There are some parts that are untranslated at the beginning of the posts, maybe you could help adding a translation. Also, it would be great if you could review the PR in general since I don't understand Chinese :).

**Comment by wusyong** [comment]
Hello, just saw the reddit post and wondering is it possible for me to also translate Traditional Chinese `zh-tw` at the same time? I have had a look on @luojia65 's work and it seems pretty good already. However, there are still some grammar and terminology differences between them. I would like to make a translation on `zh-tw`, or if you agree, convert it from Simplified Chinese.

**Comment by phil-opp** [comment]
@wusyong 

> Hello, just saw the reddit post and wondering is it possible for me to also translate Traditional Chinese `zh-tw` at the same time?

Sure! Just open a pull request against the `translations` branch.

>  I would like to make a translation on `zh-tw`, or if you agree, convert it from Simplified Chinese.

@luojia65 Is it ok with you if your translation is converted?

**Comment by phil-opp** [comment]
As a side note: We currently have the problem that the project specifies no license for the blog posts and the translations. The result is that every translator always needs to ask for permission, e.g. when converting other translations. It's also a bit dangerous for me to host translations created by other people with such an unclear copyright situation.

Therefore I plan to add a explicit license for the blog content, likely [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/). This license would then also apply to contributed translations, which would greatly simplify things. What do you think about this?

**Comment by wusyong** [comment]
@phil-opp Thanks! Adding explicit license would be great. Don't worry about permission to convert if you guys have any difficulty. I could still start from scratch anyway since I have read this before.

**Comment by luojia65** [comment]
@phil-opp I wonder if publishing paperback translated books would be applicable after one given license. (Just asking, in case of possibility. I still agree to donate my translated text.)

**Comment by phil-opp** [comment]
(I'm not a lawyer, so th following might be inaccurate or incorrect.) 

I think the current status without a license is that no rights for the blog content are automatically granted. That means you have to explicitly ask me for permission when you want to copy my content or create derivative work (like a translation). Publishing a paperback book requires my permission too.

The same applies when someone else wants to publish a paperback book of your translation: they require explicit permission of both me (the original author) and you (the translator).

The idea of a license is that it automatically grants certain rights to everybody under certain conditions. This means that no explicit permission is required for certain operations, e.g. for hosting a copy of the content somewhere else. For things not allowed by the license you need to explicitly ask for permission, just like without a license.

Let's look at the CC BY-NC license: It does not grant any rights for commercial use, which includes selling a book, so you need to ask for permission before doing it. This does not mean that it's forbidden to publish a book, you just have to make an agreement with all copyright holders. So it also means that I would have to ask you for permission before I can publish a book containing your translation, which seems fair to me.

Other things, like publishing the content online or creating derivative translations, are automatically permitted by the license, so there is no need to ask for permission in these cases. This protects us all from copyright claims, for example no one can suddenly revoke these rights and require fees for hosting the content or the translation.

I hope this clears things up!

**Comment by luojia65** [comment]
@phil-opp That seems nice, I'd agree with adding a license. Thanks for your reference explanation!

**Comment by luojia65** [comment]
Added CC-BY-SA-4.0 to my work.

**Comment by luojia65** [comment]
Added CC-BY-NC-4.0 license to our community work. 
If any questions please reply me:  https://github.com/rustcc/writing-an-os-in-rust/blob/master/LICENSE

**Comment by phil-opp** [comment]
I just added a CC BY-NC license to the blog in #705.

@TheBegining Are you willing to license your contributions under the CC BY-NC license too? This would be required for merging your translation included in this PR. If yes, please reply with:

> I hereby license my contributions to this pull request under the CC BY-NC license (https://creativecommons.org/licenses/by-nc/4.0/).

**Comment by TheBegining** [comment]
@phil-opp 
I hereby license my contributions to this pull request under the CC BY-NC license (https://creativecommons.org/licenses/by-nc/4.0/).

**Comment by phil-opp** [comment]
The Zola 0.10 branch was just merged: https://github.com/getzola/zola/pull/811. I expect that the new Zola version will be released any moment. I will update the master branch of this repo to switch to the new version and then update this pull request. Then we should be able to merge this together with #694 :tada:.

**Comment by phil-opp** [comment]
The translated content is now live at https://os.phil-opp.com/zh-CN/ and https://os.phil-opp.com/zh-TW/. Please file pull requests or issues for any rendering errors. And of course, feel free to translate more content if you like!

**Comment by phil-opp** [comment]
Regarding the "Provide a way to switch languages, at least from the index page" task from the pull request description: I added a simple language selector to both the index and the post pages in #752.

**Pull request merged**
