### PR TITLE
Use misspell tool to look for common typos

### PR DESCRIPTION
**Pull request by phil-opp**
This PR fixes some typos on the blog and adds a typo check to the CI job.

@alex-bender Thanks for suggesting misspell!

### CODE REVIEW

**Comment by alex-bender** [comment]
I'm glad to be useful! But seems that installation step failed.

**Comment by phil-opp** [comment]
> But seems that installation step failed.

Looks fine to me:

image

I think the check for the commit failed because the branch was merged (with green CI) and deleted before the job ran. The master branch is also green after the merge.

**Comment by alex-bender** [comment]
image
Here is what I saw.
Anyways that's good that it's working now.
I'm looking forward to start coding in Rust! And to get some solid knowledge on OS development.
Thanks again for the materials.

**Comment by phil-opp** [comment]
Ah yeah, this is because Github hides the status checks of merges by default. If you click "view details" you should see the same thing as I did.



> I'm looking forward to start coding in Rust! And to get some solid knowledge on OS development.
> Thanks again for the materials.

Awesome, let me know if have any questions!

**Comment by alex-bender** [comment]
wow, didn't know that. Thanks!

**Pull request merged**
