### PR TITLE
Fix type name: `EntryFlags` instead of `TableEntryFlags`

### PR DESCRIPTION
**Pull request by phil-opp**
[Reported by FreeFull](http://os.phil-opp.com/modifying-page-tables.html#comment-2466158032)

### CODE REVIEW

**Comment by FreeFull** [comment]
Hm, doesn't it actually make more sense for it to be `Entry::flags` rather than `EntryFlags::flags`? Having the method on `EntryFlags` would either be a no-op or not work.

**Comment by phil-opp** [comment]
You're completely right, it should be `Entry::flags`

**Comment by phil-opp** [comment]
Would you mind sending a quick pull request? I'm on mobile right now and can't fix it.

**Comment by FreeFull** [comment]
Will do.

**Pull request merged**
