### PR TITLE
Translate part to Chinese

### PR DESCRIPTION
**Pull request by TheBegining**
This is a great article, its content is not very complicated, but it is a bit time consuming for non-native English speakers. 
So I translated a small part into Chinese. 
If the author has a plan to translate into other languages, I believe that more people will contribute.

### CODE REVIEW

**Comment by AntoineSebert** [comment]
I know you spent time working on these translations, but I think the maintainer should put his efforts in writing new parts of the OS and their dedicated posts instead of translating the existing ones.

And who is going to translate the rest of the posts to chinese, or to other languages ?
More important, if the posts are translated in other languages, how will the maintainer respond to their issue tickets, comments and pull requests if they are also written in those languages ?

It could be a good idea, but I would categorize it as a bit too ambitious and energy-consuming for this repository. "The Hell is paved of good intentions".

**Comment by TheBegining** [comment]
You are right.

**Comment by phil-opp** [comment]
@TheBegining Sorry for not replying earlier, I was very busy.

I already received some translation requests, mainly for Chinese and Japanese. Unfortunately, I don't know these languages, so it would be difficult for me to maintain the translated content (i.e. keeping it up to date and responding to issues etc.). However, maybe it's still a good idea to try given that there is so much interest. We could add a red warning on top of each translated post that says something like "This post is just a community translation and might be out of date or inaccurate. Please report any issues in English."

I try to investigate the new translation support of Zola (our static site generator) based on this PR in the `chinese-translation` branch.

Just for your information: There are already a few unofficial translations in other repositories, e.g. https://github.com/rustcc/writing-an-os-in-rust for Chinese.

**Comment by Rustin-Liu** [comment]
If we are going to provide official translation support, I would love to contribute and support.

**Comment by phil-opp** [comment]
@Rustin-Liu Awesome, thanks! I think we can try it as an experiment and see whether it works in practice.

**Comment by phil-opp** [comment]
I opened https://github.com/phil-opp/blog_os/pull/692 to add experimental translation support to the blog. This pull request is already included in the `translations` branch, so we can close it.

**Pull request closed without merging**
