### PR TITLE
Copyedit edition 2 paging-introduction/index.md

### PR DESCRIPTION
**Pull request by bolded**
Only issues regarding hyphens, commas, and minor grammar mistakes were affected.

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot, looks all good to me! There is some overlap with https://github.com/phil-opp/blog_os/pull/1123. I think it's easiest if we merge that PR first and then integrate your changes on top of it. I hope this okay with you.

**Comment by phil-opp** [comment]
@bolded I tried to merge your changes with the ones from #1123. Please double-check my conflict resolution as there were multiple instances where the same sentences were modified.

@hecatia-elegua If you have time, it would be great if you could take quick a look at this PR too. It add some more corrections on top of your recent changes.

**Review by hecatia-elegua — APPROVED** [review]
allow to control the caches / allow the control of caches
seems stylistic, but doesn't change the meaning so all good :+1:

**Comment by phil-opp** [comment]
Thanks for reviewing!

**Pull request merged**
