### PR TITLE
Fix travis by cleaning libraries built with stale nightly compiler

### PR DESCRIPTION
**Pull request by robert-w-gries**
Travis is currently failing with the following message:

```
36.08s$ make
   Compiling core v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling std_unicode v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd_unicode)
   Compiling alloc v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc)
    Finished release [optimized] target(s) in 34.81 secs
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling blog_os v0.1.0 (file:///home/travis/build/phil-opp/blog_os)
error[E0460]: found possibly newer version of crate `core` which `rlibc` depends on
  --> src/lib.rs:23:1
   |
23 | extern crate rlibc;
   | ^^^^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: the following crate versions were found:
           crate `core`: /home/travis/.xargo/lib/rustlib/x86_64-blog_os/lib/libcore-58f01dc603992338.rlib
           crate `rlibc`: /home/travis/build/phil-opp/blog_os/target/x86_64-blog_os/debug/deps/librlibc-8eabc116dc6e8246.rlib
```

[I have hit the same issue in my repo](https://travis-ci.org/robert-w-gries/rxinu/jobs/318464189#L586), and I believe the issue is that Travis caches the previously built libraries.  The failure is triggered when Travis pulls in a new nightly compiler and attempts to build our kernel with libraries built by an old nightly compiler.

The solution is to ensure our libraries are built with the latest nightly compiler.  I accomplished this by running `make clean` before building the kernel.

### CODE REVIEW

**Comment by robert-w-gries** [comment]
[Here you can see where Travis is caching our newly built dependencies](https://travis-ci.org/phil-opp/blog_os/builds/319261384#L632).

It might be possible to tell Travis to skip caching these dependencies, but I was not able to find this option.

**Comment by robert-w-gries** [comment]
The issue appears intermittent, since Travis is currently passing.

[Here's the link to the original Travis failure](https://travis-ci.org/phil-opp/blog_os/builds/318767546).

**Comment by robert-w-gries** [comment]
I've found the root cause of the problem.

[From Travis's docs for `cache: cargo`](https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache)

> This caches $HOME/.cargo and $TRAVIS_BUILD_DIR/target.

So instead of using `cache: cargo`, we can do something like this:

```diff
-cache: cargo
+cache:
+  directories:
+    - $HOME/.cargo
```

**Comment by phil-opp** [comment]
Thanks for investigating! I noticed the error several times, but didn't had the time to look into it. I worked around it by manually clearing the cache and restarting the failed builds.

The problem is still not clear to me. We used the current nightly compiler and the cargo cache on travis for at least a year without problems and suddenly it fails. Does the same problem occur locally (e.g. when compiling, then updating the nightly version, and then compiling again)? If yes, this would be a bug in cargo or xargo.

**Comment by phil-opp** [comment]
I just found https://github.com/japaric/xargo/issues/185, which seems related.

**Comment by robert-w-gries** [comment]
That Xargo issue is related to `core` compiling twice.  I believe that issue is triggered when multiple dependencies are listed in `Xargo.toml` and the incorrect staging order is given.

Honestly, I'm not sure what triggered the issue in our CI.  The problem came up a few weeks ago for `rxinu` and didn't go away until I added the naive `make clean` solution.

My theory is that cargo made a change to how it detects dependencies, which hid the underlying issue of caching our project dependencies.

rust-lang/cargo#4763 seems like it could have caused this change in behavior.

To verify that a change in dependency checking is the issue, I've collected the following logs:

### [Passing Travis Build with `rust-lang/cargo#4763` changes included](https://travis-ci.org/phil-opp/blog_os/builds/318222654#L515)

Note that our dependencies are re-compiled (such as `bitflags`).

```
   Compiling core v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling std_unicode v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd_unicode)
   Compiling alloc v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc)
    Finished release [optimized] target(s) in 37.13 secs
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling bitflags v0.4.0
   Compiling once v0.3.3
   Compiling volatile v0.1.0
   Compiling bitflags v0.9.1
   Compiling rlibc v1.0.0
   Compiling bit_field v0.7.0
   Compiling spin v0.4.6
   Compiling multiboot2 v0.1.0
   Compiling x86_64 v0.1.2
   Compiling lazy_static v0.2.11
   Compiling linked_list_allocator v0.4.3
   Compiling blog_os v0.1.0 (file:///home/travis/build/phil-opp/blog_os)
```

### [Failing Travis build with `rust-lang/cargo#4763` changes included](https://travis-ci.org/phil-opp/blog_os/builds/318767546#L515)

Note that `bitflags` dependency is not re-compiled.

```
   Compiling core v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling std_unicode v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd_unicode)
   Compiling alloc v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc)
    Finished release [optimized] target(s) in 34.81 secs
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling blog_os v0.1.0 (file:///home/travis/build/phil-opp/blog_os)
```

### [Passing Travis build without changes included](https://travis-ci.org/phil-opp/blog_os/builds/306874709)

```
   Compiling core v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling std_unicode v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd_unicode)
   Compiling alloc v0.0.0 (file:///home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc)
    Finished release [optimized] target(s) in 27.99 secs
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling volatile v0.1.0
   Compiling bitflags v0.4.0
   Compiling bit_field v0.7.0
   Compiling rlibc v1.0.0
   Compiling bitflags v0.9.1
   Compiling spin v0.4.6
   Compiling once v0.3.3
   Compiling multiboot2 v0.1.0
   Compiling x86_64 v0.1.2
   Compiling lazy_static v0.2.11
   Compiling linked_list_allocator v0.4.2
   Compiling blog_os v0.1.0 (file:///home/travis/build/phil-opp/blog_os)
```

### Conclusion

I do not have the time to check every Travis build before `rust-lang/cargo#4763` was merged, but I suspect that Travis always re-compiled our project dependencies like `bitflags`.  Now that the cargo cache is properly checked, we're hitting an issue with the underlying problem of caching our project dependencies when they shouldn't be cached.

**Comment by robert-w-gries** [comment]
I'm able to trigger the issue locally in my own kernel.

I modified my `Xargo.toml` (note that I use `compiler_builtins` for `stage = 1` in my kernel):

```diff
diff --git a/Xargo.toml b/Xargo.toml
index a16927a..a7fbf75 100644
--- a/Xargo.toml
+++ b/Xargo.toml
@@ -1,10 +1,4 @@
-[target.i686-rxinu.dependencies]
-alloc = {}
-
-[target.x86_64-rxinu.dependencies]
-alloc = {}
-
-[dependencies.core]
+[dependencies.alloc]
 stage = 0
```

I then started seeing the `newer version of crate 'core'`  issue come up more frequently in my project.  I found the only consistent way to trigger the issue is as follows:

```
git checkout feature/i686-scheduling
make clean # start clean to ensure we're triggering the issue
make
git checkout feature/test-framework
make # the build will fail until we run `make clean`
```

It looks to be the same issue we saw in `blog_os`'s Travis failure:

```
$ make
   Compiling core v0.0.0 (file:///home/rob/.rustup/toolchains/nightly-2017-12-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling std_unicode v0.0.0 (file:///home/rob/.rustup/toolchains/nightly-2017-12-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd_unicode)
   Compiling alloc v0.0.0 (file:///home/rob/.rustup/toolchains/nightly-2017-12-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc)
    Finished release [optimized] target(s) in 24.22 secs
   Compiling compiler_builtins v0.1.0 (file:///home/rob/.rustup/toolchains/nightly-2017-12-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcompiler_builtins)
    Finished release [optimized] target(s) in 2.45 secs
    Updating git repository `https://github.com/japaric/utest`
    Updating registry `https://github.com/rust-lang/crates.io-index`            
   Compiling rxinu v0.1.0 (file:///home/rob/rxinu)
error[E0460]: found possibly newer version of crate `core` which `bitflags` depends on
  --> src/lib.rs:18:1
   |
18 | extern crate bitflags;
   | ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: the following crate versions were found:
           crate `core`: /home/rob/.xargo/lib/rustlib/x86_64-rxinu/lib/libcore-0671f1c158fe3776.rlib
           crate `bitflags`: /home/rob/rxinu/target/x86_64-rxinu/debug/deps/libbitflags-bed2609b99acd464.rlib
```

It looks like there is an issue with Xargo, but I'm still of the opinion that caching the project dependencies is a waste of time since we re-compile them anyway 😃

**Comment by robert-w-gries** [comment]
I'll close the PR until there is clarification on the issue: japaric/xargo#189

**Pull request closed without merging**
