### PR TITLE
Add (initial) Japanese translation

### PR DESCRIPTION
**Pull request by JohnTitor**
This is the first step for adding the Japanese translations.
The first post translation is taken from https://github.com/JohnTitor/blog-os-ja/blob/master/src/01-freestanding-rust-binary.md.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Oh, we should update the entry anyway, one sec...

**Comment by JohnTitor** [comment]
Okay, this is now ready to review :)
cc @phil-opp

**Comment by phil-opp** [comment]
I don't know Japanese, so I can't review the translation itself. I think it's probably best to just merge this and let people file issues if they have any improvement suggestions.

Thanks for contributing your translation!

**Comment by JohnTitor** [comment]
> I don't know Japanese, so I can't review the translation itself. I think it's probably best to just merge this and let people file issues if they have any improvement suggestions.

Yeah, that's a reasonable way. I think we could announce starting Japanese translations here in the next monthly report so that more people notice it :)

**Comment by phil-opp** [comment]
Yeah, I try to remember to mention it in the next post.

**Comment by woodyZootopia** [comment]
Is there any progress on this issue? I'm impressed by this blog and want to contribute in translation to Japanese.

**Comment by JohnTitor** [comment]
@woodyZootopia Well, anyone can translate the posts, feel free to submit a PR :) I'm happy to review it.

**Comment by woodyZootopia** [comment]
@JohnTitor Thank you! I'm starting translation of "A Minimal Rust Kernel", so please review it when it's done~

**Comment by woodyZootopia** [comment]
I found that @phil-opp is rewriting this chapter for edition 2.1, so I'll wait until it's done.

**Comment by phil-opp** [comment]
> I found that @phil-opp is rewriting this chapter for edition 2.1, so I'll wait until it's done.

Yes, I am. However, this will probably take a while until I publish it since all the other posts need to be updated as well.

I saw that you started translating the post in https://github.com/phil-opp/blog_os/pull/871. Since I don't speak Japanese, it's difficult to review it, so maybe @JohnTitor can take a look.

**Pull request merged**
