### PR TITLE
Fix typo (therefor -> therefore)

### PR DESCRIPTION
**Pull request by Lewn**
I am not a native English speaker, so I am not 100% sure this is correct, but from the information I found on https://www.translegal.com/legal-english-lessons/therefore-vs-therefor , it looks like in this case, the word "therefore" is correct.

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot! I'm not a native speaker either, so I'm not 100% sure about this... 

The `remap-the-kernel` change looks good to me, but I think we should reword the sentence in `page-tables`. Something like "We implement it using the `FrameAllocator` from..." or "For the implementation we need the `FrameAllocator` from...". What do you think?

**Comment by Lewn** [comment]
I think that "For the implementation we need the FrameAllocator from..." would read the easiest.

**Comment by phil-opp** [comment]
Ok, thanks! Could you include it in the PR?

**Comment by Lewn** [comment]
Done :)

**Comment by phil-opp** [comment]
Thanks a lot!

**Pull request merged**
