### PR TITLE
Correction of Japanese

### PR DESCRIPTION
**Pull request by asami-kawasaki**
## summary
The following Japanese has been corrected because it has a different meaning.

## corresponding passage
Before change
```
コンパイラに `Unpin` を【選択】させることで、
```

After change
```
コンパイラに `Unpin` を【オプトアウト】させることで、
```

### CODE REVIEW

**Comment by kahirokunn** [comment]
LGTM

**Comment by phil-opp** [comment]
Thank you! And thanks to @kahirokunn for reviewing!

One thing that I'm not sure about is the translators list. The current list only includes the people that substantially contributed to the initial translation added in https://github.com/phil-opp/blog_os/pull/977, but not people who contributed minor corrections afterwards (e.g. in https://github.com/phil-opp/blog_os/pull/1036). These contributions are still very valuable of course, the question is just if we want to add them to the same list as the initial translators.

So we have two possibilities, which both have their advantages and drawbacks:

- Add all contributors to the list, independent of their contibutions
  - All contributions are credited
  - The list will then grow very long over time
  - The initial translators are equally credited as people who fixed a typo
- Only add the initial translators to the list and leave it unchanged on later corrections.
  - Maybe we could have a separate list for more minor contributions, e.g. named `contributors`
  - We need to decide whether a contribution is "major enough" to be credited

What do you think?

cc'ing the other people in the list: @kahirokunn @garasubo @sozysozbot @woodyZootopia

**Comment by kahirokunn** [comment]
Contributions like this one are also important and will only be a better resource if they are actively made.

Maybe contributions like this one are best written on a separate list.

**Comment by kahirokunn** [comment]
I hope many people can correct mistranslations like this one.

I think solved by the design of the website is better.

**Comment by kahirokunn** [comment]
I explain how this occurred.
I asked `asami-kawasaki` to review the translation of this article.
`asami-kawasaki` had read the translation in detail, found several corrections, and contributed to it.
So, I said to `asami-kawasaki` put `asami-kawasaki` in the list of translators.
asami-kawasaki just did the job as instructed.

**Comment by garasubo** [comment]
I don't have strong opinion on it. Either way is fine for me.

**Comment by phil-opp** [comment]
Ok, thanks a lot for your thoughts! Sounds like a separate contributors list is the best solution. I'll implement this in the template, then I will merge this PR.

> Contributions like this one are also important and will only be a better resource if they are actively made.

Yes, absolutely! Contributions like this are very valuable and we definitely want to encourage them. I hope that my earlier comment did not come across otherwise... So thanks a again for your work @asami-kawasaki and sorry for this whole discussion!

**Comment by phil-opp** [comment]
I added the new field in #1112 and merged this PR as part of #1113.

**Pull request merged**
