### PR TITLE
Add French translation of post 2 ("A Minimal Rust Kernel")

### PR DESCRIPTION
**Pull request by TheMimiCodes**
This pull request adds a French translation of the second post (A Minimal Rust Kernel).

### CODE REVIEW

**Comment by TheMimiCodes** [comment]
@phil-opp Hello! This is a pull request for Hacktoberfest, it's ready for review. If you deem it acceptable but can't approve it or merge it, could you add the `hacktoberfest-accepted` label to it? Thank you! 😃

**Comment by phil-opp** [comment]
Hi @TheMimiCodes, thanks a lot for this PR!

cc @AlexandreMarcq @alaincao If you have time, it would be great if you could take a quick look at this PR.

**Comment by musabagwan** [comment]
Un noyau de rouille minimal

**Comment by alaincao** [comment]
Hi, sorry, I missed the original notification mail. I just saw this today ...

I was not sure how I can make suggestions using a commit on a PR, so I made PR on the PR ;-)
There:
https://github.com/TheMimiCodes/blog_os/pull/1
so @TheMimiCodes can double-check.

- I updated some local links to point to the FR pages when available, but 'not sure if they will work correctly.
  I am not too familiar with markdown and could not test on a running application
- I also modified links to the FR Wikipedia pages when they existed
- I saw a lot of links like "[xxx][yyy]" or "\[xxx](yyy)",
  sometimes translations is on the left, sometimes on the right?
	  I am not too sure how things work. Maybe someone else should review them.
- I have no idea what an "associations mémoire" is, but I 100% understand what a "memory map" is.  
  I would vote for leaving those technical terms as they are...
- I "untranslated" those:
	- caisses -> crates: this is Rust "technical terms", not a "real" words
	- bibliothèque essentielle -> bibliothèque `core`: this is the name of the library
	- méthode caractéristique -> méthode _trait_: this is Rust "technical terms", not a "real" words
- I changed
	- "Imprimer" -> "afficher": "Imprimer" now sound to me heavily linked to "printers" and not to "screens" anymore.  
  	  Gone is the time of the teletypes !
	- "Noter" -> "Notez": sounds to me a lot less "informal/imperative". As we say in french "détendu du slip" (relaxed from the thong?)

All in all, those are only suggestions. I have french-belgian ears, and I think the author is french-canadian (?), so things probably sounds very different ...

**Comment by fzingg** [comment]
Hi,
I did a review on that POST-02 FRENCH version made by @TheMimiCodes and updated by @alaincao.
I'm a french (France) native speaker.
I think that POST-02 french translation is almost perfect and can by merged.
I find your work @phil-opp you did on that blog is amazing.
I will keep reading and doing translation for the next posts.

**Comment by phil-opp** [comment]
Thanks a lot for reviewing @fzingg! 

@TheMimiCodes Could you look through https://github.com/TheMimiCodes/blog_os/pull/1 and merge the changes you agree with? After that we can merge :tada:.

**Comment by fzingg** [comment]
@phil-opp If we do not have news from @TheMimiCodes and @alaincao in the next weeks, let me know if you want I copy the POST-02 french page and do a new PR.

**Comment by TheMimiCodes** [comment]
I merged @alaincao's recommended changes in my branch, so this pull request is now ready to review once more. Thank you everyone for reviewing this translation!

**Review by fzingg — APPROVED** [review]
Translation is now very good in french. 
I think it can be merged.

**Comment by phil-opp** [comment]
Great, thanks again everyone!

Published at <https://os.phil-opp.com/fr/minimal-rust-kernel/>.

**Comment by phil-opp** [comment]
> This is a pull request for Hacktoberfest, it's ready for review. If you deem it acceptable but can't approve it or merge it, could you add the `hacktoberfest-accepted` label to it? Thank you! smiley

@TheMimiCodes We don't need that label, given that it's merged now, right?

**Comment by TheMimiCodes** [comment]
@phil-opp Correct, you can remove the label if you want. Thanks for asking!

**Pull request merged**
