### PR TITLE
Korean translation for ch-01

### PR DESCRIPTION
**Pull request by JOE1994**
Hello :smiley_cat: , 
I finished translating the first post of the blog series to Korean.
I locally built the website with zola to see how the translated page is rendered.
I reviewed the translation several times to correct any mistakes.

Thank you for your hard work on this blog series :+1: :+1:

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot for creating the translation! The boilerplate looks good to me, but since don't speak Korean, I'm not able to review the content. Maybe we can find someone to review this by including this our the next [_This Month in Rust OSDev_](https://rust-osdev.com/) newsletter. This means a delay of about two weeks before we can merge this, I hope this is ok with you.

**Comment by JOE1994** [comment]
> Thanks a lot for creating the translation! The boilerplate looks good to me, but since don't speak Korean, I'm not able to review the content. Maybe we can find someone to review this by including this our the next [_This Month in Rust OSDev_](https://rust-osdev.com/) newsletter. This means a delay of about two weeks before we can merge this, I hope this is ok with you.

That works for me 👍

**Comment by QuqqU** [comment]
I was thinking of translating it, but there was someone who already translated it!
I think I can help reviewing the Korean translation, and translating documents that haven't been translated yet.
If you need, feel free to tag me!

p.s. your homepage about os-in-rust is very helpful for me to implement OS in rust!

**Comment by JOE1994** [comment]
@QuqqU It'd be great if you could review this PR 👍
If you are willing to work on Korean translations for other posts, I'd be eager to help with reviewing 😺

**Comment by QuqqU** [comment]
Everything is fine!
I reviewed it in detail, and all the sentences are translated exactly as the original author wishes.
I wish this  is helpful. @phil-opp phil-opp

**Review by QuqqU — COMMENTED** [review]
Everything is fine!
I reviewed it in detail, and all the sentences are translated exactly as the original author wishes.

**Review by QuqqU — APPROVED** [review]

**Comment by phil-opp** [comment]
Thanks a lot for reviewing!

**Pull request merged**
