### PR TITLE
Translate post 11 "allocator design" into Japanese

### PR DESCRIPTION
**Pull request by swnakamura**
TTSIA. I've just started working on it, but made a WIP PR to avoid possible duplicate works.

### CODE REVIEW

**Comment by woodyZootopia** [comment]
Translation finished on my side. I was busy and lazy so it took way more than I thought initially... Sorry for the delay.
If some of @JohnTitor @garasubo @shimomura1004 or anybody else had free time and kindness to review my translation, I would appreciate it more than anything!

**Comment by swnakamura** [comment]
Since everybody seems to be busy, I double-checked the translation by myself. If anybody finds any suggestions/corrections for my translations later, I'd appreciate it at any time.
@phil-opp I believe this PR is ready for merge. Could you merge it?

**Review by phil-opp — APPROVED** [review]
Yes, of course! Thanks a lot for all your work on this!

**Comment by garasubo** [comment]
Sorry for late response. I'll review your translation next time.

**Pull request merged**
