### PR TITLE
Translate Multitasking post to Chinese

### PR DESCRIPTION
**Pull request by ssrlive**

### CODE REVIEW

**Comment by acyanbird** [comment]
Hi are you finish translate it? Can I convert this to simplified Chinese?

**Comment by ssrlive** [comment]
Finished. Of cause you can.

**Comment by acyanbird** [comment]
Thanks! www

**Comment by phil-opp** [comment]
Thanks a lot for creating this translation!

@wusyong If you have time, maybe you could take a quick look at this translation?

**Comment by phil-opp** [comment]
Ok, let's just merge this without a review. Thanks again for creating this translation @ssrlive and sorry for the long delay!

**Comment by ssrlive** [comment]
Thanks. I think this translation is serious.

**Pull request merged**
